language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
cache: pip

install:
  - pip install -r requirements.txt
  - sudo apt install prodigal

branches:
  only:
    - master

script:
  - pytest tests/
