language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
cache: pip

install:
  - pip install -r requirements.txt
  - sudo apt install prodigal
  - wget https://github.com/marbl/Mash/releases/download/v2.0/mash-Linux64-v2.0.tar
  - tar xf mash-Linux64-v2.0.tar
  - export PATH=$PATH:$PWD/mash-Linux64-v2.0

branches:
  only:
    - master

script:
  - pytest tests/
